server.port=3000

tiingo.api.base-url=https://api.tiingo.com/tiingo/daily
tiingo.api.token=fc9a0e23dde6d1fd1757a6c222057af4b6948d21

finnhub.api.base-url=https://finnhub.io/api/v1
finnhub.api.token=d2adjghr01qoad6pbgv0d2adjghr01qoad6pbgvg

stock.excel.filename=Stocks.xlsx
stock.excel.sheet=Sheet1